language: node_js

node_js:
- "10.3.0"

install:
- npm install
- pip install --user awscli

before_script:
- npm run verify

script:
- npm run build

deploy:

- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  region: us-east-1
  local_dir: build
  bucket: cuffney.com
  on:
    branch: master

after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"