language: node_js

node_js:
- "10.3.0"

# cache:
#   directories:
#     - "node_modules"

install:
- npm install

script:
- npm run build
- ls -la build/

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  region: us-east-1
  local_dir: build
  bucket: v2.cuffney.com

branches:
  only:
  - master