language: node_js

node_js:
- "10.3.0"

install:
- npm install
- pip install --user awscli

script:
- npm run build

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  region: us-east-1
  local_dir: build
  bucket: v2.cuffney.com
  on:
    branch: master

- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  region: us-east-1
  local_dir: build
  bucket: cuffney.com
  on:
    tags: true

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"