# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build
          command: npm run build

      # run tests!
      - run:
          name: test
          command: yarn test

      # TODO: can pip/awscli be cached?
      - run:
          name: Install PIP
          command: sudo apt-get install python-pip python-dev

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync ./build s3://cuffney.com --delete --region=us-east-1
            else
              echo "Not master branch, dry run only"
            fi

      - run:
        name: Create CloudFront Invalidation
        command: |
          aws cloudfront create-invalidation \
          --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
          --paths "/*"
