version: 2
jobs:
  build:
    docker:
      - image: circleci/node-browsers:11.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install PIP
          command: sudo apt-get install python-pip python-dev

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: validate cloudformation template
          command: |
            aws cloudformation validate-template \
              --template-body file://template.yml \
              --region us-east-1

      - run:
          name: build
          command: npm run build

      - run:
          name: lint
          command: npm run lint

      - run:
          name: test
          command: yarn test

      - run:
          name: cover
          command: npm run cover

      - run:
          name: end to end testing
          command: npm run test:e2e
      
      - run:
          name: deploy infrastructure
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws cloudformation update-stack \
                --stack-name cuffney-com \
                --template-body file://template.yml
            # elif [ "${CIRCLE_BRANCH}" = "dev" ]; then
            #   aws cloudformation update-stack \
            #     --stack-name cuffney-com \
            #     --template-body file://template.yml
            else
              echo "Not master branch, dry run only"
            fi

      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync ./build s3://cuffney.com --delete
            # elif [ "${CIRCLE_BRANCH}" = "dev" ]; then
            #   aws s3 sync ./build s3://dev.cuffney.com --delete
            else
              echo "Not master branch, dry run only"
            fi

      - deploy:
          name: Create CloudFront Invalidation
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws cloudfront create-invalidation \
                --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
                --paths "/*"
            # elif [ "${CIRCLE_BRANCH}" = "dev" ]; then 
            #   aws cloudfront create-invalidation \
            #     --distribution-id $DEV_CLOUDFRONT_DISTRIBUTION_ID \
            #     --paths "/*"
            else
              echo "Not master branch, dry run only"
            fi
