defaults: &defaults
  docker: 
    - image: circleci/node:11.0
  working_directory: ~/repo

version: 2
jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build: 
    <<: *defaults
    steps:
      - checkout
      - run: npm run build
 

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - dependencies
      # - build:
      #     requires:
      #       - dependencies
      # - lint:
      #     requires:
      #       - dependencies
      # - coverage:
      #     requires:
      #       - dependencies
      # - e2e_tests:
      #     requires: 
      #       - dependencies
      # - test_deploy:
      #     requires: 
      #       - dependencies
      #     filters:
      #       only: dev
      # - prod_deploy:
      #     requires: 
      #       - dependencies
      #     filters:
      #       only: master
      